# Generated by Django 3.1.2 on 2020-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='capacity',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
    ]
