# Generated by Django 3.1.2 on 2020-11-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20201117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='XXX', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ManyToManyField(related_name='medicines', to='pharmacy.Category'),
        ),
    ]
