# Generated by Django 3.1.2 on 2020-12-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_auto_20201220_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(default=True)),
                ('medicine_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicineorder')),
            ],
        ),
    ]
