# Generated by Django 3.1.2 on 2021-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20210103_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineorder',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.AlterModelOptions(
            name='newordermessage',
            options={'ordering': ['-started']},
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='orderStatus',
            field=models.CharField(choices=[('Placed', 'Placed'), ('In preparation', 'In preparation'), ('Ready to pick up', 'Ready to pick up'), ('Finished', 'Finished')], default='Placed', max_length=100),
        ),
    ]
